influxdb:
  auth:
    admin:
      password: '#Set in ArgoCD'
      token: '#Set in ArgoCD'
    user:
      username: rddl
      password: '#Set in ArgoCD'
      org: rddl_network
      bucket: validator_notarization
    readUser:
      username: read
      password: '#Set in ArgoCD'
    writeUser:
      username: write
      password: '#Set in ArgoCD'
  fullnameOverride: influxdb
  persistence:
    storageClass: r3c-prod-client-nfs

grafana:
  admin:
    password: '#Set in ArgoCD'
  fullnameOverride: grafana
  grafana:
    initContainers:
      - name: init-influxdb
        image: busybox:1.28
        command: ['sh', '-c', "until nc -vz influxdb 8086; do echo waiting for influxdb; sleep 2; done"]
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    ingressClassName: haproxy
    hostname: info.rddl.io
    tls: true
  persistence:
    storageClass: r3c-prod-client-nfs
