# Default values for rddl-info.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/rddl-network/rddl-info
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

schedule: "* * * * *"

concurrencyPolicy: Replace

suspend: false

restartPolicy: OnFailure

terminationGracePeriodSeconds: 0

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  labels: {}
  annotations: {}
  existingClaim: ""
  mountPath: /usr/src/app/data
  size: 128Mi
