version: '2.1'

services:
  influxdb:
    image: influxdb:2.6.1
    volumes:
      - ./influxdb2:/var/lib/influxdb2
    ports:
      - "8086:8086"
  grafana:
    depends_on:
      - influxdb
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/lib:/var/lib/grafana
      - ./grafana/etc:/etc/grafana
      - ./grafana/log:/var/log/grafana
    user: 'root'

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    user: 'root'
  rddl_info:
    depends_on:
      - influxdb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
    environment:
      - INFLUXDB_TOKEN="SP1uc-ZXBhULXOZco5OFb7k8Gy_RdvIlU09USt8dB5llpwHuZc42D6vpmjximz85xDNUpkHTXe-if23AyL8FjQ=="
      - INFLUXDB_ORG="RDDL Network"
      - INFLUXDB_BUCKET="b0c82ebece524afe"
      - INFLUXDB_HOST_URL="http://influxdb:8086"
    entrypoint: /bin/sh
